### ISSUE TITLE
Uncaught TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by timoa** [tcarlsen/atom-jslint#24]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: [jslint](https://github.com/tcarlsen/atom-jslint) package, v1.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'data' of undefined

```
At /Users/tthdlx/.atom/packages/jslint/node_modules/atom-message-panel/lib/MessagePanelView.js:206

TypeError: Cannot read property 'data' of undefined
  at [object Object].MessagePanelView.resizeStopped (/Users/tthdlx/.atom/packages/jslint/node_modules/atom-message-panel/lib/MessagePanelView.js:206:6)
  at [object Object].MessagePanelView.close (/Users/tthdlx/.atom/packages/jslint/node_modules/atom-message-panel/lib/MessagePanelView.js:108:12)
  at /Users/tthdlx/.atom/packages/jslint/lib/linter.coffee:48:14
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app/src/pane-container.js:347:34
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:264:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:328:21)
  at tabs-tab.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:184:24)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
     -3:05.2 core:backspace (atom-text-editor.editor)
     -3:05.1 editor:newline (atom-text-editor.editor)
     -3:03.5 core:backspace (atom-text-editor.editor)
     -3:03.3 editor:newline (atom-text-editor.editor)
     -3:02.1 core:backspace (atom-text-editor.editor)
     -3:02.0 editor:newline (atom-text-editor.editor)
     -3:00.5 core:backspace (atom-text-editor.editor)
  2x -3:00.3 editor:newline (atom-text-editor.editor)
     -2:58.0 core:backspace (atom-text-editor.editor)
  3x -2:56.7 core:save (atom-text-editor.editor)
     -2:02.5 core:copy (atom-text-editor.editor)
     -2:01.3 find-and-replace:show (atom-text-editor.editor)
  6x -0:20.3 core:backspace (atom-text-editor.editor)
     -0:14.7 core:save (atom-text-editor.editor)
  2x -0:10.4 core:undo (atom-text-editor.editor)
     -0:08.4 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
javascript-snippets, v1.0.0
jsdoc, v0.9.0
jslint, v1.2.0
language-javascript-semantic, v0.1.0
language-tss, v0.0.2
linter, v0.11.1
ti-build-atom, v0.7.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by tcarlsen** [comment]
Thx for reporting this. I will look into the problem on Monday. (on vacation atm)



—

**Comment by KillerCodeMonkey** [comment]
same here and a thanks for looking into it

**Comment by tcarlsen** [comment]
this is an issue in AMP `1.2.0` https://github.com/tcarlsen/atom-message-panel/issues/65

**Comment by tcarlsen** [comment]
this issue is fixed in AMP but I believe you need to reinstall jslint for the package to redownload to the new AMP version

**Comment by garethbjohnson** [comment]
Thanks! Reinstalling reinstalling the jslint package worked for me.
