### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by haydenbleasel** [tcarlsen/atom-jslint#25]
1. Open any file
2. Command-S to save
3. JSLint errors appear
4. Click on an error...

**Atom Version**: 0.181.0
**System**: Mac OS X 10.9.5
**Thrown From**: [jslint](https://github.com/tcarlsen/atom-jslint) package, v1.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At /Users/haydenbleasel/.atom/packages/jslint/node_modules/atom-message-panel/lib/LineMessageView.js:51

TypeError: Cannot read property 'path' of undefined
    at LineMessageView.goToLine (/Users/haydenbleasel/.atom/packages/jslint/node_modules/atom-message-panel/lib/LineMessageView.js:51:58)
    at HTMLPreElement.<anonymous> (/Users/haydenbleasel/.atom/packages/jslint/node_modules/atom-message-panel/node_modules/space-pen/lib/space-pen.js:214:36)
    at HTMLPreElement.jQuery.event.dispatch (/Users/haydenbleasel/.atom/packages/jslint/node_modules/atom-message-panel/node_modules/space-pen/vendor/jquery.js:4676:9)
    at HTMLPreElement.elemData.handle (/Users/haydenbleasel/.atom/packages/jslint/node_modules/atom-message-panel/node_modules/space-pen/vendor/jquery.js:4360:46)
```

### Commands

```
     -0:43.1 core:move-down (atom-text-editor.editor)
  2x -0:42.9 core:move-right (atom-text-editor.editor)
     -0:36.5 core:save (atom-text-editor.editor)
     -0:34.1 core:copy (atom-text-editor.editor)
     -0:22.2 find-and-replace:show (atom-text-editor.editor)
     -0:19.5 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:19.5 core:cancel (atom-text-editor.editor.mini)
     -0:18.7 core:paste (atom-text-editor.editor)
     -0:18.3 core:save (atom-text-editor.editor)
     -0:08.1 fuzzy-finder:toggle-file-finder (ul.list-inline.tab-bar.inset-panel)
     -0:07.4 core:backspace (atom-text-editor.editor.mini)
     -0:06.8 core:confirm (atom-text-editor.editor.mini)
     -0:05.7 fuzzy-finder:toggle-file-finder (atom-text-editor.editor)
  3x -0:04.4 core:backspace (atom-text-editor.editor.mini)
     -0:03.4 core:confirm (atom-text-editor.editor.mini)
     -0:01.2 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {},
  "jslint": {}
}
```

### Installed Packages

```coffee
# User
atom-spotify, v1.2.0
autocomplete-plus, v2.1.6
compare-files, v0.4.1
editorconfig, v0.3.0
emmet, v2.3.3
jslint, v1.2.0
jsonlint, v1.0.1
language-batch, v0.3.2
language-jade, v0.3.0

# Dev
No dev packages
```

**Comment by tcarlsen** [comment]
this was a problem in ATM at it has been fixed..

you have to uninstall and reinstall the package to solve the problem... sry
