### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by r0n22** [tcarlsen/atom-jslint#26]
[Enter steps to reproduce below:]

1. JSLint Error shown
2. Click on Error to go to Line

**Atom Version**: 0.176.0
**System**: linux 3.18.7-200.fc21.x86_64
**Thrown From**: [jslint](https://github.com/tcarlsen/atom-jslint) package, v1.2.0

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /home/cregan/.atom/packages/jslint/node_modules/atom-message-panel/lib/LineMessageView.js:51

TypeError: Cannot read property '0' of undefined
  at [object Object].LineMessageView.goToLine (/home/cregan/.atom/packages/jslint/node_modules/atom-message-panel/lib/LineMessageView.js:51:60)
  at HTMLPreElement.<anonymous> (/home/cregan/.atom/packages/jslint/node_modules/atom-message-panel/node_modules/space-pen/lib/space-pen.js:214:36)
  at HTMLPreElement.jQuery.event.dispatch (/home/cregan/.atom/packages/jslint/node_modules/atom-message-panel/node_modules/space-pen/vendor/jquery.js:4676:9)
  at HTMLPreElement.elemData.handle (/home/cregan/.atom/packages/jslint/node_modules/atom-message-panel/node_modules/space-pen/vendor/jquery.js:4360:46)

```

### Commands

```
     -1:54.6 core:save (atom-text-editor.editor)
  7x -1:45.5 core:backspace (atom-text-editor.editor)
     -1:38.0 core:select-right (atom-text-editor.editor)
     -1:37.6 core:cut (atom-text-editor.editor)
  2x -1:37.1 core:move-right (atom-text-editor.editor)
  2x -1:36.6 core:move-left (atom-text-editor.editor)
     -1:35.8 core:undo (atom-text-editor.editor)
  2x -1:35.3 core:backspace (atom-text-editor.editor)
 14x -1:17.8 core:undo (atom-text-editor.editor)
     -0:30.8 core:confirm (atom-text-editor.editor.mini)
     -0:10.2 core:save (atom-text-editor.editor)
     -0:03.6 core:backspace (atom-text-editor.editor)
     -0:03.2 core:move-left (atom-text-editor.editor)
  3x -0:02.9 core:move-right (atom-text-editor.editor)
     -0:02.3 core:backspace (atom-text-editor.editor)
     -0:01.9 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "isotope-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
isotope-ui, v1.6.0
jslint, v1.2.0
minimap, v4.1.3
pretty-json, v0.3.2
wordpress-api, v1.1.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by tcarlsen** [comment]
the update should fix this

**Comment by tcarlsen** [comment]
you need to refresh atom after update `ctrl + alt + cmd + l`
