### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by eugenebalaban** [tcarlsen/atom-jslint#32]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.192.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.2
**Thrown From**: [jslint](https://github.com/tcarlsen/atom-jslint) package, v1.3.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/eugene/.atom/packages/jslint/lib/config.coffee:6

TypeError: undefined is not a function
  at module.exports (/Users/eugene/.atom/packages/jslint/lib/config.coffee:6:61)
  at module.exports (/Users/eugene/.atom/packages/jslint/lib/linter.coffee:20:38)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1111:25

```

### Commands

```
     -8:34.3 editor:indent (atom-text-editor.editor)
     -8:33.5 core:backspace (atom-text-editor.editor)
     -6:45.2 core:confirm (atom-text-editor.editor.mini)
     -5:07.1 styleguide:show (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -4:25.5 autoflow:reflow-selection (atom-text-editor.editor)
     -4:20.2 core:undo (atom-text-editor.editor)
     -4:07.2 window:toggle-dev-tools (atom-text-editor.editor)
     -2:55.2 http-status-codes:show (atom-text-editor.editor)
     -2:47.2 grammar-selector:show (atom-text-editor.editor)
 12x -1:41.0 core:backspace (atom-text-editor.editor.mini)
     -1:36.6 core:confirm (atom-text-editor.editor.mini)
     -0:22.3 jslint:lint (atom-text-editor.editor.is-focused)
     -0:09.6 core:select-all (atom-text-editor.editor.is-focused)
     -0:07.8 jslint:lint (atom-text-editor.editor.is-focused)
     -0:01.3 editor:newline (atom-text-editor.editor.is-focused)
     -0:00.2 core:move-left (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "jslint": {
    "validateOnChange": true
  }
}
```

### Installed Packages

```coffee
# User
http-status-codes, v1.0.3
jsdoc, v0.9.0
jslint, v1.3.0
linter, v0.12.0
linter-js-standard, v0.1.4

# Dev
No dev packages
```

**Comment by tcarlsen** [comment]
thx for reporting :+1: 

fixed in new version :smile:
