### ISSUE TITLE
Failed to load the jslint package

### ISSUE THREAD

**Issue by pablobb** [tcarlsen/atom-jslint#41]
[Enter steps to reproduce below:]

1. just open the atom.io

**Atom Version**: 1.0.19
**System**: Microsoft Windows 8.1
**Thrown From**: [jslint](https://github.com/tcarlsen/atom-jslint) package, v1.4.0

### Stack Trace

Failed to load the jslint package

```
At Cannot find module 'atom-message-panel'

Error: Cannot find module 'atom-message-panel'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\Paweł\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Paweł\.atom\packages\jslint\lib\linter.coffee:1:57)
    at Object.<anonymous> (C:\Users\Paweł\.atom\packages\jslint\lib\linter.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\Paweł\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-ruby",
      "ruby-block",
      "ruby-block-converter",
      "remote-edit",
      "script"
    ],
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.6.1
atom-message-panel-service, v0.0.1-1
autoclose-html, v0.19.0
jquery-snippets, v11.0.0
jslint, v1.4.0
Remote-FTP, v0.7.4
wordpress-api, v1.2.1

# Dev
No dev packages
```

**Comment by tcarlsen** [comment]
looks like the `npm install` command failed to run, so try removing the jslint and reinstall

**Comment by pablobb** [comment]
Still same error, maybe i should try install sth manually ?

**Comment by tcarlsen** [comment]
this is very wierd, and not quite sure how this is happening
